# Generated by Django 4.2.11 on 2024-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='register_date',
            field=models.DateField(null=True),
        ),
    ]
